name: progress_bar_rounded
description: A customizable rounded progress bar widget for Flutter with smooth animations, multiple themes, and flexible child widget support.
version: 1.0.1
homepage: https://github.com/AnshRajput/progress-bar
repository: https://github.com/AnshRajput/progress-bar
issue_tracker: https://github.com/AnshRajput/progress-bar/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
