name: progress_bar
description: A customizable rounded progress bar widget for Flutter with smooth animations, multiple themes, and flexible child widget support.
version: 1.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.16.0
